"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 21:53:54.324441
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sections',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('course_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('section_id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('test', 'quiz', 'homework', 'project', name='assessmentkind'), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_section_id'), ['section_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_section_id'), ['section_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'tardy', 'absent', 'excused', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'day')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('insights',
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_student_id'), ['student_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('assessment_id', sa.String(length=12), nullable=False),
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_student_id'))
        batch_op.drop_index(batch_op.f('ix_scores_assessment_id'))

    op.drop_table('scores')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_student_id'))

    op.drop_table('notes')
    op.drop_table('insights')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_day'))

    op.drop_table('attendance')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_section_id'))
        batch_op.drop_index(batch_op.f('ix_students_name'))

    op.drop_table('students')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_section_id'))

    op.drop_table('assessments')
    op.drop_table('sections')
    op.drop_table('courses')
    # ### end Alembic commands ###
